### ISSUE TITLE
Support lightgbm >= 3

### ISSUE THREAD

**Issue by memeplex** [microsoft/hummingbird#389] opened 2020-12-14 00:35 UTC
setup.py requires lightgbm < 3, I'm using the current version of lightgbm so hummingbird reports that it's not installed. Is there any blocking incompatibility or is it just that the requirement version is out of date?

**Comment by memeplex** [comment] 2020-12-14 00:37
Not the same, but related https://github.com/microsoft/hummingbird/issues/282

**Comment by interesaaat** [comment] 2020-12-14 00:41
I think we just didn't test it with >= 3. We found #282 when we tried with v3. As far as I remember this was the only problem, so beside random forest it should just work.

**Comment by memeplex** [comment] 2020-12-14 00:44
That was fast! It's weird that it is complaining that lightgbm is not installed then, but if you say it should work I will give it another try and let you know, thanks!

**Comment by interesaaat** [comment] 2020-12-14 00:51
I saw warning that the version is not supported etc., but not real errors. So if the complaining is just a warning, I think it should work. Otherwise if you installed from source, you can just change `setup.py` and remove the `<3` for lightgbm.

**Comment by memeplex** [comment] 2020-12-14 00:56
Ok, another similar issue is that it wants to downgrade numpy from 1.19.4, do you think it would be a problem if I keep 1.19.4, now that I'm in the business of forcing dependencies?

And even more OT: currently I'm using onnxtools, which is compiling to the tree ensamble operator (in the ML set) that is later evaluated by onnx runtime (C++ code that more or less straightforwardly evals the ensamble). Should I expect a significative performance gain if I compile without the ML set using hummingbird?

**Comment by memeplex** [comment] 2020-12-14 01:15
Ok, I've been trying again, this was my test code:

```python
from hummingbird.ml import convert
import numpy as np
import lightgbm as lgb
import timeit
 
import onnxruntime as ort
from onnxmltools.convert import convert_lightgbm
from onnxconverter_common.data_types import FloatTensorType

max_depth = 4
n_estimators = 100
n_features = 100
n_classes = 2
n_cats = 20
n_fit = 10000
n_pred = 10
X_fit = np.random.randint(n_cats, size=(n_fit, n_features)).astype(np.float32)
y_fit = np.random.randint(n_classes, size=n_fit)

model = lgb.LGBMClassifier(n_estimators=n_estimators, max_depth=max_depth)
model.fit(X_fit, y_fit, categorical_feature=list(range(n_features)))

input_types = [("input", FloatTensorType((n_pred, n_features)))]
onnx_model = convert_lightgbm(model, initial_types=input_types)
hum_onnx_model = convert(model, 'onnx', extra_config={"initial_types": input_types})
hum_torch_model = convert(model, 'pytorch')
```

`convert_lightgbm` in onnxtools works fine, but both attempts to convert using hummingbird failed:

1. onnx backend:

```
MissingConverter: Unable to find converter for SklearnLGBMClassifier type <class 'NoneType'> with extra config: {'initial_types': [('input', FloatTensorType(shape=(10, 100)))], 'container': True, 'n_threads': 2, 'tree_implementation': 'tree_trav', 'post_transform': <function convert_gbdt_common.<locals>.apply_sigmoid at 0x11ef0eb80>}.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.
Please fill an issue at https://github.com/microsoft/hummingbird.
```

2. pytorch backend:

```
~/Projects/Jampp/Venvs/LTV/lib/python3.8/site-packages/hummingbird/ml/operator_converters/_tree_implementations.py in depth_f_traversal(node, current_depth, node_id, leaf_start_id)
    359         def depth_f_traversal(node, current_depth, node_id, leaf_start_id):
    360             weight_0[node_id] = node.feature
--> 361             bias_0[node_id] = -node.threshold
    362             current_depth += 1
    363             node_id += 1

TypeError: bad operand type for unary -: 'str'
```

Maybe this is related to lightgbm version, maybe not, but I have no clue.

**Comment by interesaaat** [comment] 2020-12-14 03:24
This is with lgbm 3.0m right? I am worried that to return that error they changed the encoding of the tree. I will take a look. 

BTW, Hummingbird is already integrated with onnxmltools and the lgbm converter. You can translate into onnx op sets by using the flag `without_onnx_ml=True` (but I guess it will not work because of a similar exception as above).

Regarding the performance, are you testing on CPU of GPU? For GPU we should definitely be faster (than CPU). For CPU, I don't think we will be faster if you using the onnx runtime (to get the best performance you will have to use TVM as backend) but it might, it depends on the number of trees and max tree-depth.

**Comment by memeplex** [comment] 2020-12-14 03:41
> BTW, Hummingbird is already integrated with onnxmltools and the lgbm converter. You can translate into onnx op sets by using the flag without_onnx_ml=True

I know but it has not been released yet and I am stuck with the stable release for now.

I'm using CPU right now but part of what I'm trying to do is testing GPU performance. About 100 trees with 4-5 depth, pretty standard ensamble.

I'm not in my computer but lgb version is the latest stable one, I believe 3.1 or so. Definitely > 3.

Thanks for the advice.

**Comment by ksaur** [comment] 2020-12-14 05:16
Regarding `Ok, another similar issue is that it wants to downgrade numpy from 1.19.4`; as far as I know this works.  Other users have mentioned issues about the numpy downgrade (#372 ), and I  *think* it is ok since for now you're already `in the business of forcing dependencies`  :-D  Please let us know if you have issues with that!

**Comment by memeplex** [comment] 2020-12-14 15:22
@interesaaat one thing I should have mentioned is that the example above uses categorical variables, maybe they are not supported by hummingbird?

AFAICS lightgbm encodes the split subsets like `n1||n2||n3||..||nk` and one of the errors I get when trying to convert the ensamble is like:

```
could not convert string to float: '2||4||6||7'
```

Looking at the onnx tree ensamble operator specification I don't see direct support for such stuff, all comparisons seem to be against numbers. So I'm not sure whether it is supported at all or maybe a transformation happens first in the graph, I'm still investigating that. Now, hummingbird is a different beast so it might still support categorical features through non ML operators.

**Comment by memeplex** [comment] 2020-12-14 15:28
Also the comparison is codified as `==` in those cases:

![image](https://user-images.githubusercontent.com/2845433/102100001-b195a680-3e07-11eb-9514-fc84250dc286.png)

So only by inspecting the threshold it is possible to recognize it is a set operation and not simply numerical equality.

**Comment by memeplex** [comment] 2020-12-14 15:45
Here is something about onnx (and onnx tools) not supporting that feature: https://github.com/onnx/onnxmltools/issues/309

**Comment by interesaaat** [comment] 2020-12-14 17:30
Ah-ha! This explain the error. Yes, neither onnxmltools nor Hummingbird (#245) support categorical values in the trees, yet. Do you want to give it a shot? :) 

The easy way would be to add a one-hot encoder right before the tree, but perhaps we can do something better. We already convert strings into 2d tensors of numbers, perhaps we can use a similar trick here.

**Comment by memeplex** [comment] 2020-12-14 18:34
For onnx / onnxmltools maybe the way to go is to add support for set membership in the operator definition itself and implement it in the runtime in a straightforward way.

> We already convert strings into 2d tensors of numbers, perhaps we can use a similar trick here.

Could you expand on this a bit more?

**Comment by ksaur** [comment] 2021-06-19 23:22
@interesaaat, was there one lingering test/issue you wanted to look at (`@unittest.skipIf(True, reason="boosting_type=='rf' produces different probabilites.")`),  or does #523 close this since we support lgbm`>=3`?

**Comment by interesaaat** [comment] 2021-06-19 23:48
Yes let me take a look at that test. If it does not work I can try to fix it.

**Comment by ksaur** [comment] 2022-01-07 22:00
Can we close this since we support lgbm>=3 and we concluded that it wasn't the cause?  It seems like the issue here is now just in #245 ?

**Comment by interesaaat** [comment] 2022-01-07 23:00
Yes let's close this one. Thanks!

**Closed as completed** 2022-01-07 23:00 UTC
