### ISSUE TITLE
sklearn RandomForestClassifier with random_state=42 breaks conversion 

### ISSUE THREAD

**Issue by ValentinMuhr** [microsoft/hummingbird#380] opened 2020-12-08 16:22 UTC
Hi, 
I tried to convert a sklearn RandomForestClassifier model to PyTorch.
The parameter random_state seems to break the conversion process when set to '42'.
I have tried different random_stat values and they all worked well, except form '42'.

    def random_forest(X_train, y_train, jobs):
    
        clf  = RandomForestClassifier(criterion="entropy", min_samples_split=2, random_state=42, n_jobs=jobs)
        clf.fit(X_train, y_train)
    
        return clf

    ####### Random Forests ######
    def train_rf(case):
        print("Training Random Forest:", case)
    
        clf = random_forest(train["X_train_" + case], train["y_train_" + case], -1)
    
        save_model(clf, "clf_rf_" + case, clf_dir, len(train["X_train_" + case].columns))
    
        return clf

    clf = train_rf(cases_to_train[0])

    model = convert(clf, 'torch')

> MissingConverter: Unable to find converter for SklearnRandomForestClassifier type <class 'NoneType'> with extra config: {'container': True, 'n_threads': 4, 'n_trees': 100}.
It usually means the pipeline being converted contains a
transformer or a predictor with no corresponding converter implemented.

But if I change random_state to a different number the conversion will run through:

    def random_forest(X_train, y_train, jobs):
    
        clf  = RandomForestClassifier(criterion="entropy", min_samples_split=2, random_state=21, n_jobs=jobs)
        clf.fit(X_train, y_train)
    
        return clf

Please find attached, the complete error log.
[error_log.txt](https://github.com/microsoft/hummingbird/files/5660422/error_log.txt)

**Comment by ValentinMuhr** [comment] 2020-12-08 16:25
Edit: It seems that not only '42' creates this issue but also other values.
But still some values work fine.

**Comment by interesaaat** [comment] 2020-12-08 16:26
Thanks @ValentinMuhr for reporting this. This is clearly a bug. The problem is that with some `random_state` some tree in the forest will be empty, and this breaks conversion. We had few test cases for this already, but apparently they are not covering all cases! Will send a fix soon.

**Comment by interesaaat** [comment] 2020-12-08 17:26
@ValentinMuhr any chance you can replicate the error with a random dataset (or the ones provided in Sklearn)? 

I tried with this test and I cannot replicate the error.
```
# Random forest classifier empty tree
# Test for this issue: https://github.com/microsoft/hummingbird/issues/380
def random_forest_empty_tree(self):
        warnings.filterwarnings("ignore")
        np.random.seed(0)
        X = np.random.rand(100, 200)
        X = np.array(X, dtype=np.float32)
        y = np.random.randint(2, size=100)

        model = RandomForestClassifier(criterion="entropy", min_samples_split=2, random_state=42)
        model.fit(X, y)
        torch_model = hummingbird.ml.convert(model, "torch")
        self.assertIsNotNone(torch_model)
        np.testing.assert_allclose(model.predict_proba(X), torch_model.predict_proba(X), rtol=1e-06, atol=1e-06)
```

**Comment by ksaur** [comment] 2022-03-10 20:02
@ValentinMuhr I'm going to close this due to staleness; if you are still blocked or can share the datatset with us, please reopen or file a new one, thanks!

**Closed as completed by ksaur** 2022-03-10 20:02 UTC
Labels: bug
