### ISSUE TITLE
Slower than original implementation on CPU

### ISSUE THREAD

**Issue by zhanjiezhu** [microsoft/hummingbird#177] opened 2020-07-05 19:29 UTC
Does it make sense if the converted pytorch model is slower than the original sklearn model when run on CPU?
Here are the results when I run the "blog_example" notebook:

Time scikit-learn:
45.4 ms ± 1.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

Time PyTorch - CPU:
138 ms ± 2.36 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

**Comment by interesaaat** [comment] 2020-07-05 22:58
Hello! Yes sometimes we are not faster, but for the blog example we should. Which version of pytorch did you use?

**Comment by zhanjiezhu** [comment] 2020-07-06 07:31
Hi, the torch version is 1.5.1.
Though when I import hummingbird, I got this "ONNX runtime not installed. Please check https://github.com/microsoft/onnxruntime#installation for instructions."

Did this affect the speed?

**Comment by interesaaat** [comment] 2020-07-06 15:32
Nope, that is something we already fixed, it is not impacting performance. Could you please try with Pytorch 1.4? We are seeing 10x performance degradation with the latest Pytorch.

**Comment by zhanjiezhu** [comment] 2020-07-06 15:52
you're right, downgrading to pytorch 1.4 leads to 10x faster:
13.3 ms ± 363 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Comment by interesaaat** [comment] 2020-07-07 00:09
I was going to pin pytorch version to 1.4.0 (until the performance problems are fixed) but unfortunately onnxruntime is throwing a seg fault with pytorch 1.4.0 (likely due to some exporting bug). So for the moment we will have to live with this.

**Comment by interesaaat** [comment] 2020-07-09 01:03
We [checked](https://github.com/pytorch/pytorch/issues/41057) with the PyTorch folks and the problem is already fixed in the next release. Closing the issue.

**Closed as completed by interesaaat** 2020-07-09 01:03 UTC
