### ISSUE TITLE
RuntimeError: CUDA out of memory on Windows

### ISSUE THREAD

**Issue by onacrame** [microsoft/hummingbird#176] opened 2020-06-30 10:14 UTC
I run the following code below in Colab 
```
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from lightgbm import LGBMClassifier
from hummingbird.ml import convert


X, y = make_classification(n_samples=200000, n_features=100, n_informative=5,
                           n_redundant=5, n_classes=11, n_clusters_per_class=2, 
                           random_state=0)

model = LGBMClassifier(n_estimators=100, max_depth=10,objective='multilogloss')
results = pd.DataFrame(columns=["Model", "Method", "Result"])

model.fit(X, y)
hum_model = convert(model, 'pytorch')
hum_model.to('cuda')

base_time = %timeit -n 3 -o model.predict(X)
hum_time = %timeit -n 3 -o hum_model.predict(X)
results.loc[len(results)] = ['LGBM', "Base", np.mean(base_time.all_runs)]
results.loc[len(results)] = ['LGBM', "Hummingbird with Cuda", np.mean(hum_time.all_runs)]
```

And I get this result:

> 3 loops, best of 3: 19.9 s per loop
> 3 loops, best of 3: 2.03 s per loop

Good result, looks like on this multiclass problem Hummingbird results in a 10x pickup on inference speed.  I try this code in Windows, however, and have the RuntimeError below.  I have a 16 core AMD machine and an RTX 2080TI GPU with 11GB of ram.  I'm not running anything else in the background, which is why this error baffles me.

> Finished loading model, total used 100 iterations
> 799 ms ± 9.96 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-1-a1b236580653> in <module>
>      22 # time models
>      23 base_time = get_ipython().run_line_magic('timeit', '-n 3 -o model.predict(X)')
> ---> 24 hum_time = get_ipython().run_line_magic('timeit', '-n 3 -o hum_model.predict(X)')
>      25 results.loc[len(results)] = ['LGBM', "Base", np.mean(base_time.all_runs)]
>      26 results.loc[len(results)] = ['LGBM', "Hummingbird with Cuda", np.mean(hum_time.all_runs)]
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
>    2315                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
>    2316             with self.builtin_trap:
> -> 2317                 result = fn(*args, **kwargs)
>    2318             return result
>    2319 
> 
> <decorator-gen-61> in timeit(self, line, cell, local_ns)
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
>     185     # but it's overkill for just that one bit of state.
>     186     def magic_deco(arg):
> --> 187         call = lambda f, *a, **k: f(*a, **k)
>     188 
>     189         if callable(arg):
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\IPython\core\magics\execution.py in timeit(self, line, cell, local_ns)
>    1162                     break
>    1163 
> -> 1164         all_runs = timer.repeat(repeat, number)
>    1165         best = min(all_runs) / number
>    1166         worst = max(all_runs) / number
> 
> e:\Continuum\miniconda3\envs\testenv\lib\timeit.py in repeat(self, repeat, number)
>     203         r = []
>     204         for i in range(repeat):
> --> 205             t = self.timeit(number)
>     206             r.append(t)
>     207         return r
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\IPython\core\magics\execution.py in timeit(self, number)
>     167         gc.disable()
>     168         try:
> --> 169             timing = self.inner(it, self.timer)
>     170         finally:
>     171             if gcold:
> 
> <magic-timeit> in inner(_it, _timer)
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\hummingbird\ml\_container.py in predict(self, *inputs)
>      90             return self.forward(*inputs).cpu().numpy().flatten()
>      91         else:
> ---> 92             return self.forward(*inputs)[0].cpu().numpy()
>      93 
>      94 
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\hummingbird\ml\_container.py in forward(self, *inputs)
>      56             for operator in self.operators:
>      57                 pytorch_op = self.operator_map[operator.full_name]
> ---> 58                 pytorch_outputs = pytorch_op(*(variable_map[input] for input in operator.input_full_names))
>      59 
>      60                 if len(operator.output_full_names) == 1:
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
>     548             result = self._slow_forward(*input, **kwargs)
>     549         else:
> --> 550             result = self.forward(*input, **kwargs)
>     551         for hook in self._forward_hooks.values():
>     552             hook_result = hook(self, input, result)
> 
> e:\Continuum\miniconda3\envs\testenv\lib\site-packages\hummingbird\ml\operator_converters\_tree_implementations.py in forward(self, x)
>     351             gather_indices = torch.index_select(nodes, 0, prev_indices).view(-1, self.num_trees)
>     352             features = torch.gather(x, 1, gather_indices).view(-1)
> --> 353             prev_indices = factor * prev_indices + torch.ge(features, torch.index_select(biases, 0, prev_indices)).long().view(
>     354                 -1
>     355             )
> 
> RuntimeError: CUDA out of memory. Tried to allocate 1.64 GiB (GPU 0; 11.00 GiB total capacity; 8.36 GiB already allocated; 373.74 MiB free; 8.38 GiB reserved in total by PyTorch)

If I change the number of samples to 20,000 it works fine, but query why 200,000 causes an issue on the GPU.  By the way, in the case of 20,000 samples the improvement is not as good.  

> LGBM Native
> 86.2 ms ± 5.84 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)
> LGBM GPU
> 49.8 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 3 loops each)

Maybe it's due the number of cores/clock speed difference vs Colab. Any thoughts on any of the above?

**Comment by ksaur** [comment] 2020-06-30 15:56
Interesting, thank you for these details!  I haven't worked with GPU+windows much, but we can dig into this and get back to you!  It would be great to get to the root cause.

**Comment by interesaaat** [comment] 2020-06-30 16:24
I think there is something fishy here. If the GPU numbers are those, I think that some operator is not executed in GPU but on CPU. Maybe this also explains the OOM error? (PyTorch need to materialize partial results between CPU and GPU) However this is likely a Pytorch issue rather then Hummingbird

**Comment by ksaur** [comment] 2022-03-10 20:04
@onacrame Closing this due to staleness; if you are still blocked please reopen!

**Closed as completed by ksaur** 2022-03-10 20:04 UTC
